export enum RESPONSE_CODE {
  SUCCESS = 0,
  PARAMS_ERROR = 40000,
  NO_LOGIN = 40001,
  AUTH_ERROR = 40002,
  DATA_NOT_FOUND = 40003,
  NO_PERMISSION = 40102,
  SYSTEM_ERROR = 50000,
  SYSTEM_MAINTENANCE = 50001,
  UNKNOWN_ERROR = 50002,
  INTERNAL_SERVICE_ERROR = 50100,
  INTERNAL_SERVICE_TIMEOUT = 50101,
  INTERNAL_SERVICE_ERROR1 = 50102,
  COMMENT_UPDATE_FAIL = 100000,
  AD_NO_CONTENT = 100001,
  NOT_DOUYIN_COMMENT = 100002,
  END_BEFORE_START = 100003,
  SYSTEM_ERROR_SINGLE_AD = 100004,
  SEARCH_OVER_LIMIT = 100005
}
export const RESPONSE_TEXT = {
  [RESPONSE_CODE.SUCCESS]: '成功',
  [RESPONSE_CODE.PARAMS_ERROR]: '参数错误',
  [RESPONSE_CODE.NO_LOGIN]: '未登录',
  [RESPONSE_CODE.AUTH_ERROR]: '权限错误',
  [RESPONSE_CODE.DATA_NOT_FOUND]: '数据不存在',
  [RESPONSE_CODE.NO_PERMISSION]: '无此操作权限',
  [RESPONSE_CODE.SYSTEM_ERROR]: '系统错误',
  [RESPONSE_CODE.SYSTEM_MAINTENANCE]: '系统维护',
  [RESPONSE_CODE.UNKNOWN_ERROR]: '未知错误',
  [RESPONSE_CODE.INTERNAL_SERVICE_ERROR]: '内部服务错误',
  [RESPONSE_CODE.INTERNAL_SERVICE_TIMEOUT]: '内部服务超时',
  [RESPONSE_CODE.INTERNAL_SERVICE_ERROR1]: '内部服务错误',
  [RESPONSE_CODE.COMMENT_UPDATE_FAIL]: '评论更新失败',
  [RESPONSE_CODE.AD_NO_CONTENT]: '广告没有推广的内容，操作失败',
  [RESPONSE_CODE.NOT_DOUYIN_COMMENT]: '非抖音评论',
  [RESPONSE_CODE.END_BEFORE_START]: '查询的结束时间必须晚于开始时间',
  [RESPONSE_CODE.SYSTEM_ERROR_SINGLE_AD]: '系统异常，暂时只支持查看单条计划',
  [RESPONSE_CODE.SEARCH_OVER_LIMIT]: '单次查询数量超过限制'
}

export enum STATUS_CODE {
  NO_PERMISSION = 401,
  NO_PERMISSION1 = 403,
  NOT_FOUND = 404,
  SYSTEM_ERROR = 500
}

export const STATUS_TEXT = {
  [STATUS_CODE.NO_PERMISSION]: '您没有权限操作',
  [STATUS_CODE.NO_PERMISSION1]: '您没有权限操作',
  [STATUS_CODE.NOT_FOUND]: '当前资源不存在',
  [STATUS_CODE.SYSTEM_ERROR]: '系统异常，请稍后重试'
}